<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();
        $countries = [
            [
                'name' => 'Nepal',
                'slug' => 'nepal',
                'code' => 'NP',
                'phone_code' => '+977',
                'flag' => 'https://flagcdn.com/w80/np.png',
                'description' => 'Nepal, home to eight of the world\'s highest peaks including Mount Everest, offers breathtaking landscapes from the Himalayas to the Terai plains. Rich in cultural heritage with ancient temples, stupas, and vibrant festivals, Nepal is a paradise for trekkers, adventure seekers, and spiritual travelers.',
                'image' => 'https://picsum.photos/seed/nepal/1200/600',
                'currency' => 'NPR',
                'currency_symbol' => '₨',
                'language' => 'Nepali',
                'timezone' => 'Asia/Kathmandu',
                'capital' => 'Kathmandu',
                'population' => 30498600,
                'area' => 147516.00,
                'visa_info' => 'Tourist visa available on arrival for most nationalities. Valid passport required with at least 6 months validity.',
                'best_season' => 'October to December and March to May',
                'travel_tips' => 'Carry cash as cards are not widely accepted outside major cities. Always bargain in local markets. Respect local customs and dress modestly at religious sites.',
                'emergency_contacts' => 'Police: 100, Ambulance: 102, Fire: 101, Tourist Police: 1144',
                'weather_info' => 'Nepal has four major seasons: Spring (March-May), Summer/Monsoon (June-August), Autumn (September-November), Winter (December-February).',
                'status' => 1,
                'featured' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Thailand',
                'slug' => 'thailand',
                'code' => 'TH',
                'phone_code' => '+66',
                'flag' => 'https://flagcdn.com/w80/th.png',
                'description' => 'Thailand, known as the Land of Smiles, boasts stunning tropical beaches, ornate temples, bustling markets, and world-renowned cuisine. From the vibrant streets of Bangkok to the serene islands of the south, Thailand offers an unforgettable travel experience.',
                'image' => 'https://picsum.photos/seed/thailand/1200/600',
                'currency' => 'THB',
                'currency_symbol' => '฿',
                'language' => 'Thai',
                'timezone' => 'Asia/Bangkok',
                'capital' => 'Bangkok',
                'population' => 69950800,
                'area' => 513120.00,
                'visa_info' => 'Visa-free entry for many countries for up to 30 days. Extension available at immigration offices.',
                'best_season' => 'November to February',
                'travel_tips' => 'Learn basic Thai phrases. Be cautious with street food hygiene. Dress appropriately when visiting temples. Tuk-tuks should be negotiated before ride.',
                'emergency_contacts' => 'Police: 191, Ambulance: 1669, Fire: 199, Tourist Police: 1155',
                'weather_info' => 'Tropical climate with three seasons: Hot (March-June), Rainy (July-October), Cool (November-February).',
                'status' => 1,
                'featured' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Japan',
                'slug' => 'japan',
                'code' => 'JP',
                'phone_code' => '+81',
                'flag' => 'https://flagcdn.com/w80/jp.png',
                'description' => 'Japan seamlessly blends ancient traditions with cutting-edge modernity. From serene temples and traditional tea ceremonies to neon-lit Tokyo and bullet trains, Japan offers a unique cultural experience found nowhere else on earth.',
                'image' => 'https://picsum.photos/seed/japan/1200/600',
                'currency' => 'JPY',
                'currency_symbol' => '¥',
                'language' => 'Japanese',
                'timezone' => 'Asia/Tokyo',
                'capital' => 'Tokyo',
                'population' => 125700000,
                'area' => 377975.00,
                'visa_info' => 'Visa-free for many countries for up to 90 days. Ensure passport is valid for entire stay.',
                'best_season' => 'March to May and October to November',
                'travel_tips' => 'Purchase a JR Pass for train travel. Learn basic etiquette like bowing and removing shoes. Cash is still widely used.',
                'emergency_contacts' => 'Police: 110, Ambulance/Fire: 119, Japan Helpline: 0570-000-911',
                'weather_info' => 'Four distinct seasons: Spring (March-May), Summer (June-August), Autumn (September-November), Winter (December-February).',
                'status' => 1,
                'featured' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Italy',
                'slug' => 'italy',
                'code' => 'IT',
                'phone_code' => '+39',
                'flag' => 'https://flagcdn.com/w80/it.png',
                'description' => 'Italy is a dream destination offering world-class art, ancient Roman history, Renaissance architecture, delectable cuisine, and stunning coastal landscapes. From the canals of Venice to the hills of Tuscany, every corner tells a story.',
                'image' => 'https://picsum.photos/seed/italy/1200/600',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'language' => 'Italian',
                'timezone' => 'Europe/Rome',
                'capital' => 'Rome',
                'population' => 59554000,
                'area' => 301340.00,
                'visa_info' => 'Part of Schengen Area. Visa-free for up to 90 days within 180-day period for many nationalities.',
                'best_season' => 'April to June and September to October',
                'travel_tips' => 'Learn a few Italian phrases. Validate train tickets before boarding. Watch for pickpockets in tourist areas. Lunch is typically 12:30-14:30.',
                'emergency_contacts' => 'Police: 112, Ambulance: 118, Fire: 115, Tourist Police: 06-4686-2100',
                'weather_info' => 'Mediterranean climate: Hot summers and mild winters. North Italy has colder winters with snow in the Alps.',
                'status' => 1,
                'featured' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Kenya',
                'slug' => 'kenya',
                'code' => 'KE',
                'phone_code' => '+254',
                'flag' => 'https://flagcdn.com/w80/ke.png',
                'description' => 'Kenya is the ultimate safari destination, home to the Great Migration, vast savannahs, diverse wildlife including the Big Five, and stunning Indian Ocean beaches. Experience authentic African culture and breathtaking natural beauty.',
                'image' => 'https://picsum.photos/seed/kenya/1200/600',
                'currency' => 'KES',
                'currency_symbol' => 'KSh',
                'language' => 'Swahili',
                'timezone' => 'Africa/Nairobi',
                'capital' => 'Nairobi',
                'population' => 53771300,
                'area' => 580367.00,
                'visa_info' => 'E-visa required for most nationalities. Apply online before travel. Yellow fever vaccination certificate may be required.',
                'best_season' => 'July to October (Great Migration) and January to February',
                'travel_tips' => 'Carry insect repellent for malaria prevention. Respect wildlife and maintain safe distance on safaris. Bargain in local markets.',
                'emergency_contacts' => 'Police: 999, Ambulance: 999, Fire: 999, Tourist Police: +254-20-272-4151',
                'weather_info' => 'Tropical climate: Warm year-round. Long rains (March-May), Short rains (October-December). Dry seasons are best for wildlife viewing.',
                'status' => 1,
                'featured' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Peru',
                'slug' => 'peru',
                'code' => 'PE',
                'phone_code' => '+51',
                'flag' => 'https://flagcdn.com/w80/pe.png',
                'description' => 'Peru is a land of ancient civilizations, home to the iconic Machu Picchu, the Sacred Valley, the Nazca Lines, and the vast Amazon rainforest. Its rich history, diverse landscapes, and vibrant culinary scene make it a top travel destination.',
                'image' => 'https://picsum.photos/seed/peru/1200/600',
                'currency' => 'PEN',
                'currency_symbol' => 'S/.',
                'language' => 'Spanish',
                'timezone' => 'America/Lima',
                'capital' => 'Lima',
                'population' => 32971800,
                'area' => 1285216.00,
                'visa_info' => 'Visa-free for many countries for up to 183 days. Valid passport required.',
                'best_season' => 'May to September (dry season)',
                'travel_tips' => 'Acclimatize to altitude in Cusco before trekking. Try local cuisine like ceviche. Carry US dollars as backup currency.',
                'emergency_contacts' => 'Police: 105, Ambulance: 106, Fire: 116, Tourist Police: 0800-22221',
                'weather_info' => 'Varies by region: Coast is mild, Highlands have wet/dry seasons, Amazon is hot and humid year-round.',
                'status' => 1,
                'featured' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Australia',
                'slug' => 'australia',
                'code' => 'AU',
                'phone_code' => '+61',
                'flag' => 'https://flagcdn.com/w80/au.png',
                'description' => 'Australia offers diverse experiences from the iconic Sydney Opera House and Great Barrier Reef to the vast Outback and unique wildlife. World-class beaches, vibrant cities, and ancient Indigenous culture await travelers.',
                'image' => 'https://picsum.photos/seed/australia/1200/600',
                'currency' => 'AUD',
                'currency_symbol' => 'A$',
                'language' => 'English',
                'timezone' => 'Australia/Sydney',
                'capital' => 'Canberra',
                'population' => 25788200,
                'area' => 7692024.00,
                'visa_info' => 'Most visitors need an ETA or visitor visa. Apply online before travel.',
                'best_season' => 'March to May and September to November',
                'travel_tips' => 'Sun protection is essential. Wildlife can be dangerous - follow safety guidelines. Tipping is not mandatory.',
                'emergency_contacts' => 'Police/Ambulance/Fire: 000, Tourist Assistance: 1300-555-727',
                'weather_info' => 'Seasons are opposite to Northern Hemisphere. North is tropical, south is temperate. Varied climate zones.',
                'status' => 1,
                'featured' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'United Arab Emirates',
                'slug' => 'united-arab-emirates',
                'code' => 'AE',
                'phone_code' => '+971',
                'flag' => 'https://flagcdn.com/w80/ae.png',
                'description' => 'The UAE is a federation of seven emirates offering ultramodern architecture, luxury shopping, vibrant nightlife, and Arabian hospitality. From the towering Burj Khalifa to desert safaris, it is a destination of superlatives.',
                'image' => 'https://picsum.photos/seed/uae/1200/600',
                'currency' => 'AED',
                'currency_symbol' => 'د.إ',
                'language' => 'Arabic',
                'timezone' => 'Asia/Dubai',
                'capital' => 'Abu Dhabi',
                'population' => 9771000,
                'area' => 83600.00,
                'visa_info' => 'Visa-free for many countries. Others can apply for e-visa or visa on arrival.',
                'best_season' => 'November to March',
                'travel_tips' => 'Dress modestly in public areas. Avoid public displays of affection. Alcohol is served in licensed venues only.',
                'emergency_contacts' => 'Police: 999, Ambulance: 998, Fire: 997, Tourist Police: 800-4438',
                'weather_info' => 'Desert climate: Extremely hot summers (40-50°C), mild winters (15-25°C). Very little rainfall.',
                'status' => 1,
                'featured' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Morocco',
                'slug' => 'morocco',
                'code' => 'MA',
                'phone_code' => '+212',
                'flag' => 'https://flagcdn.com/w80/ma.png',
                'description' => 'Morocco is a North African gem known for its vibrant souks, stunning Islamic architecture, the Sahara Desert, and the Atlas Mountains. A fusion of Arab, Berber, and European influences creates a uniquely captivating atmosphere.',
                'image' => 'https://picsum.photos/seed/morocco/1200/600',
                'currency' => 'MAD',
                'currency_symbol' => 'MAD',
                'language' => 'Arabic',
                'timezone' => 'Africa/Casablanca',
                'capital' => 'Rabat',
                'population' => 36910600,
                'area' => 710850.00,
                'visa_info' => 'Visa-free for many countries for up to 90 days. Valid passport required.',
                'best_season' => 'March to May and September to November',
                'travel_tips' => 'Bargaining is expected in souks. Dress conservatively. Try mint tea. Learn basic French or Arabic phrases.',
                'emergency_contacts' => 'Police: 19, Ambulance: 15, Fire: 15, Tourist Police: 0800-800-800',
                'weather_info' => 'Mediterranean climate on coast, continental inland, desert in south. Hot summers, mild winters.',
                'status' => 1,
                'featured' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Iceland',
                'slug' => 'iceland',
                'code' => 'IS',
                'phone_code' => '+354',
                'flag' => 'https://flagcdn.com/w80/is.png',
                'description' => 'Iceland is a land of fire and ice, featuring dramatic landscapes with volcanoes, glaciers, geysers, and waterfalls. The Northern Lights, Blue Lagoon, and otherworldly terrain make it one of the most unique travel destinations on earth.',
                'image' => 'https://picsum.photos/seed/iceland/1200/600',
                'currency' => 'ISK',
                'currency_symbol' => 'kr',
                'language' => 'Icelandic',
                'timezone' => 'Atlantic/Reykjavik',
                'capital' => 'Reykjavik',
                'population' => 366425,
                'area' => 103000.00,
                'visa_info' => 'Part of Schengen Area. Visa-free for up to 90 days within 180-day period for many nationalities.',
                'best_season' => 'June to August (summer) and September to March (Northern Lights)',
                'travel_tips' => 'Pack warm layers even in summer. Book Blue Lagoon in advance. Drive with caution on gravel roads. Tap water is safe and delicious.',
                'emergency_contacts' => 'Police/Ambulance/Fire: 112, Icelandic Tourist Assistance: +354-555-1100',
                'weather_info' => 'Subarctic oceanic climate: Cool summers (10-15°C), mild winters (-1 to 4°C). Weather changes rapidly. Midnight sun in summer, Northern Lights in winter.',
                'status' => 1,
                'featured' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('countries')->insert($countries);
    }
}
