<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GuideSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();
        $guides = [
            [
                'user_id' => null,
                'name' => 'Rajesh Sharma',
                'slug' => 'rajesh-sharma',
                'email' => 'rajesh.sharma@travels.com',
                'phone' => '+977-9851001001',
                'photo' => 'https://i.pravatar.cc/150?img=11',
                'bio' => 'Rajesh is an experienced trekking guide who has led over 100 expeditions in the Himalayas. Born and raised in the Solukhumbu region, he knows the Everest trails intimately.',
                'experience' => 12,
                'languages' => 'English, Nepali, Hindi',
                'certifications' => 'Licensed Tour Guide, Mountain Guide Certification, Wilderness First Aid',
                'specialties' => 'Trekking, Mountain Climbing, Cultural Tours',
                'rating' => 4.9,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Somchai Boonmee',
                'slug' => 'somchai-boonmee',
                'email' => 'somchai.b@travels.com',
                'phone' => '+66-812345678',
                'photo' => 'https://i.pravatar.cc/150?img=12',
                'bio' => 'Somchai is a Bangkok native with deep knowledge of Thai culture, cuisine, and hidden gems. He has been guiding tourists through Thailand for over a decade.',
                'experience' => 10,
                'languages' => 'Thai, English, Mandarin',
                'certifications' => 'Licensed Tour Guide, Cultural Heritage Specialist',
                'specialties' => 'Cultural Tours, Street Food Tours, Temple Tours',
                'rating' => 4.7,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Yuki Tanaka',
                'slug' => 'yuki-tanaka',
                'email' => 'yuki.tanaka@travels.com',
                'phone' => '+81-9012345678',
                'photo' => 'https://i.pravatar.cc/150?img=13',
                'bio' => 'Yuki is a certified tour guide from Kyoto with a passion for Japanese history, tea ceremonies, and traditional arts. She offers unique insights into Japan\'s cultural heritage.',
                'experience' => 8,
                'languages' => 'Japanese, English, Korean',
                'certifications' => 'Licensed Tour Guide, Cultural Heritage Specialist',
                'specialties' => 'Cultural Tours, Food Tours, Nature Walks',
                'rating' => 4.8,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Marco Rossi',
                'slug' => 'marco-rossi',
                'email' => 'marco.rossi@travels.com',
                'phone' => '+39-3334455667',
                'photo' => 'https://i.pravatar.cc/150?img=14',
                'bio' => 'Marco grew up in the Tuscan countryside and has an encyclopedic knowledge of Italian art, wine, and cuisine. He leads immersive cultural and culinary tours across Italy.',
                'experience' => 15,
                'languages' => 'Italian, English, French, Spanish',
                'certifications' => 'Licensed Tour Guide, Wine & Food Specialist, Cultural Heritage Specialist',
                'specialties' => 'Wine Tours, Cultural Tours, Luxury Travel, Food Tours',
                'rating' => 4.9,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Grace Nyambura',
                'slug' => 'grace-nyambura',
                'email' => 'grace.n@travels.com',
                'phone' => '+254-722123456',
                'photo' => 'https://i.pravatar.cc/150?img=15',
                'bio' => 'Grace is a passionate wildlife conservationist and safari guide from Nairobi. She has spent years studying the behavior of African wildlife in the Masai Mara.',
                'experience' => 9,
                'languages' => 'Swahili, English, Kikuyu',
                'certifications' => 'Licensed Tour Guide, Wilderness First Aid, Safari Guide Specialist',
                'specialties' => 'Wildlife Safaris, Bird Watching, Nature Photography',
                'rating' => 4.8,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Carlos Mendoza',
                'slug' => 'carlos-mendoza',
                'email' => 'carlos.m@travels.com',
                'phone' => '+51-987654321',
                'photo' => 'https://i.pravatar.cc/150?img=16',
                'bio' => 'Carlos is an Inca Trail specialist who has guided hundreds of trekkers to Machu Picchu. He shares deep knowledge of Inca history and Andean traditions.',
                'experience' => 11,
                'languages' => 'Spanish, English, Quechua',
                'certifications' => 'Licensed Tour Guide, Mountain Guide Certification, Wilderness First Aid',
                'specialties' => 'Trekking, Cultural Tours, Adventure Tours',
                'rating' => 4.6,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Fatima Al-Rashid',
                'slug' => 'fatima-al-rashid',
                'email' => 'fatima.ar@travels.com',
                'phone' => '+971-501234567',
                'photo' => 'https://i.pravatar.cc/150?img=17',
                'bio' => 'Fatima is a Dubai native who specializes in luxury and cultural tours. She offers exclusive access to VIP experiences across the UAE.',
                'experience' => 7,
                'languages' => 'Arabic, English, French',
                'certifications' => 'Licensed Tour Guide, Luxury Travel Specialist',
                'specialties' => 'Luxury Travel, Desert Safaris, City Tours, Shopping Tours',
                'rating' => 4.7,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => null,
                'name' => 'Bjorn Eriksson',
                'slug' => 'bjorn-eriksson',
                'email' => 'bjorn.e@travels.com',
                'phone' => '+354-7712345',
                'photo' => 'https://i.pravatar.cc/150?img=18',
                'bio' => 'Bjorn is an Icelandic adventurer who knows every corner of his homeland. From glacier hikes to Northern Lights hunting, he provides unforgettable experiences.',
                'experience' => 6,
                'languages' => 'Icelandic, English, Danish',
                'certifications' => 'Licensed Tour Guide, Glacier Guide Certification, Wilderness First Aid',
                'specialties' => 'Glacier Hiking, Northern Lights Tours, Adventure Tours, Photography Tours',
                'rating' => 4.9,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('guides')->insert($guides);
    }
}
